config/routes.rb
Rails.application.routes.draw do
  get 'pages/register'
  get 'pages/login'
  get 'pages/error'
  get 'pages/products'
  get 'pages/newproduct'
  get 'pages/products2'
  get 'pages/doughs'
  get 'pages/newdough'
  get 'pages/preferments'
  get 'pages/newpreferment'
  get 'pages/soakers'
  get 'pages/newsoaker'
  get 'pages/ingredient'
  get 'pages/newingredient'
  get 'pages/confirmation'
  get 'pages/customer'
  get 'pages/newcustomer'
  get 'pages/orders'
  get 'pages/neworder'

  devise_for :users
  get 'controller/ACTION' => 'controller#ACTION'
  get 'controller/ACTION' => 'controller#ACTION'
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/controller_controller.rb
class ControllerController < ApplicationController
  layout '_base'
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def register
  end

  def login
  end

  def home
  end

  def error
  end

  def products
  end

  def newproduct
  end

  def products2
  end

  def doughs
  end

  def newdough
  end

  def preferments
  end

  def newpreferment
  end

  def soakers
  end

  def newsoaker
  end

  def newingredient
  end

  def ingredient
  end

  def confirmation
  end

  def orders
  end

  def neworder
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controller_helper.rb
module ControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_base.html.erb
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>

    <title>Cocoon Bakery</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag 'paper_kit_pro/favicon.ico', rel: 'icon', type: 'image/ico' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Hind" rel="stylesheet">
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Montserrat' %>
    <link href='https://fonts.googleapis.com/css?family=Fredoka+One' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Open+Sans:400,300,600,800' %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= yield :head %>
  </head>
  <body class="<%= yield :class %>" data-features="<%= yield :features %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-danger">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <div class="container">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  </div>
<% end %>

<noscript>
  <div class="alert alert-danger">
    <div class="container">
      Please enable JavaScript on your browser for better experience.
    </div>
  </div>
</noscript>

app/views/layouts/_navbar.html.erb
<%= render "layouts/flashes" %>

app/views/layouts/application.html.erb
<%= render :layout => "layouts/base" do %>
  <%= render "layouts/navbar" %>
  <%= yield %>
<% end %>

app/views/pages/confirmation.html.erb
    <div id="navbar">
    
        <nav class="navbar navbar-default" role="navigation">
    
          <div class="container">
    
            <div class="navbar-header">
    
    
              <%= link_to "Cocoon", root_path, class: "navbar-brand" %>
    
            </div>
    
          </div><!-- /.container-fluid -->
    
        </nav>
    
    </div><!--  end navbar --> 

</div>          
<div class="whole-page">
<div class="wrapper">
  <div class="section section-white whole-page">
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <div class="tim-title text-center">
                    <h2><b>Nearly done</b></h2>
                    <p class="text-muted">We've just sent you an email confirmation to email@exampleemail.com</p>
                    <br>
                    <p>Go ahead and confirm your email. Then you're all set to get going with Cocoon :)</p>
                  </div>
              </div>
          </div>

          
          <div class="row">
                        
                            <div class="col-md-12  col-sm-12">
                              <div class="form-group">
                                  <button type="submit" class="btn btn-simple btn-block btn-default">Not recieved your confirmation email?</button>
                              </div>
                            </div>
                            </div>
                          </div>


                          <br>
                           <br>
                            <br>
                             <br>
                          
          </div>
    </div>
  </div>
</div>
</form>


    </div

app/views/pages/customer.html.erb
    <div id="navbar">
    
        <nav class="navbar navbar-default" role="navigation">
    
          <div class="container">
    
            <div class="navbar-header">
    
    
              <%= link_to "Cocoon", root_path, class: "navbar-brand" %>
    
            </div>
    
          </div><!-- /.container-fluid -->
    
        </nav>
    
    </div><!--  end navbar --> 

</div>          
<div class="whole-page">
<div class="wrapper">
  <div class="section section-white whole-page">
<div class="container">
<div class="row">
<div class="container">
      


<div class="container">
  <div class="row">
    <div class="col-md-12">
    <h3>
    Customers
    <button href="#" class="dropdown-toggle btn btn-fill btn-move-right pull-right hidden-sm hidden-xs" data-toggle="dropdown" aria-expanded="false">Add new <i class="ti-plus"></i></button>

    </h3>
    </br>
    <div class="row">
<div class="container">
<span class="dropdown">
  <button href="#" class="dropdown-toggle btn btn-default btn-fill btn-move-right visible-xs visible-sm" data-toggle="dropdown">Add new <i class="ti-plus"></i></button>
<!--                                  You can add classes for different colours on the next element -->
  
</span>
</div>
</span>
</div>

    <div class="row">
      <div class="container">
      </br>
    <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Delete</button>
    </div>
    </div>

    <div class="table-responsive">
      <table class="table">
          <thead>
              <tr>
                  <th><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label></th>
                  <th>Name</th>
                  <th>Location</th>
                  <th>Orders</th>
                  <th>Last Order</th>
                  <th>Total Spent</th>
              </tr>
          </thead>
          <tbody>
              <tr> 
                  <td class="check"><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label>
</td>                   
                  <td class="text-left"><a>Customer name</a></td>
                  <td>London, SO15 7PD</td>
                  <td>52</td>
                  <td><a>#53035</a></td>
                  <td>£5350.00</td>
              </tr>
              <tr> 
                  <td class="check"><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label>
</td>                   
                  <td class="text-left"><a>Customer name</a></td>
                  <td>London, SO15 7PD</td>
                  <td>52</td>
                  <td><a>#53035</a></td>
                  <td>£5350.00</td>
              </tr>
              <tr> 
                  <td class="check"><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label>
</td>                   
                  <td class="text-left"><a>Customer name</a></td>
                  <td>London, SO15 7PD</td>
                  <td>52</td>
                  <td><a>#53035</a></td>
                  <td>£5350.00</td>
              </tr>
              <tr> 
                  <td class="check"><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label>
</td>                   
                  <td class="text-left"><a>Customer name</a></td>
                  <td>London, SO15 7PD</td>
                  <td>52</td>
                  <td><a>#53035</a></td>
                  <td>£5350.00</td>
              </tr>
              <tr> 
                  <td class="check"><label class="checkbox" for="checkbox1">
                            <input type="checkbox" value="" id="checkbox1" data-toggle="checkbox">
                          </label>
</td>                   
                  <td class="text-left"><a>Customer name</a></td>
                  <td>London, SO15 7PD</td>
                  <td>52</td>
                  <td><a>#53035</a></td>
                  <td>£5350.00</td>
              </tr>
              
          </tbody>
      </table>
</div>


  </div>
</div>
</br>

<div class="row text-center">

<ul class="pagination"> 
    
      <li><a href="#">&laquo;</a></li>
    
      <li class="active"><a href="#">1</a></li>
    
      <li><a href="#">2</a></li>
    
      <li><a href="#">3</a></li>
    
      <li><a href="#">4</a></li>
    
      <li><a href="#">5</a></li>
    
      <li><a href="#">&raquo;</a></li>
    
    </ul>





</div>


</div>








        </div>
      </div>
    </div>
  </div>
</div>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <p class="text-center">Are you sure you want to delete this customer?</p>
      </div>
      <div class="modal-footer">
        <div class="left-side">
            <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancel</button>
        </div>
        <div class="divider"></div>
        <div class="right-side">
            <button type="button" class="btn btn-danger btn-simple">Delete</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.btn-tooltip').tooltip();
</script>
          

app/views/pages/home2.html.erb
<!-- Start navigation -->
<div class="hed">
</div>
<div class="header-wrapper">
      <div class="header" style="background-image: url('assets/laver2.jpg');
">
          <div class="filter filter-default"></div>
          <div class="container text-center">
                  <h2></h2>
                  <h3></h3>
                  <br>
                  
                  <i class="fa fa-angle-down fa-2x shake-vertical shake-constant" aria-hidden="true"></i>
                  
          </div>
      </div>
</div>
<!-- end navigation -->
<div class="wrapper">
  <div class="section text-center section-white">
      <div class="container">
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <div class="tim-title">
                    <h2>Introducing Cocoon</h2>
                  </div>
              </div>
          </div>
          </br>
          <div class="row">
              <div class="col-md-8 col-md-offset-2">
                    <p>"I wanted software that would let me keep on top of my bakery. That me and my staff could easily use to track everything from orders to delivery schedules. Cocoon has solved so many headaches - I can now spend more time actually growing my bakery. Thank you Cocoon!"</p>
                    <p><b>Duncan Glendinning</b><p>
                    <a>www.thethoughtfulbreadcompany.com</a>
              </div>
          </div>
          <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <img src="assets/image_placeholder.jpg" alt="Rounded Image" class="img-rounded img-responsive">
          </div>
          <br>
        </div>

app/views/pages/ingredient.html.erb
    <div id="navbar">
    
        <nav class="navbar navbar-default" role="navigation">
    
          <div class="container">
    
            <div class="navbar-header">
    
    
              <%= link_to "Cocoon", root_path, class: "navbar-brand" %>
    
            </div>
    
          </div><!-- /.container-fluid -->
    
        </nav>
    
    </div><!--  end navbar --> 

</div>          
<div class="whole-page">
<div class="wrapper">
  <div class="section section-white whole-page">
<div class="container">
<div class="row">
<div class="container">


<select name="huge" class="selectpicker visible-sm visible-xs" data-style="btn-info btn-fill btn-block" data-menu-style="dropdown-blue">
<option disabled selected> Choose component</option>
    
        <option selected="1">Products </option>
    
        <option value="1">Doughs </option>

        <option value="1">Levains </option>

        <option value="1">Soakers </option>

        <option value="1">Ingredients </option>
    
    </select>
  </div>
  </br>
</div>
<div class="row">
<div class="container">
<span class="dropdown">
  <button href="#" class="dropdown-toggle btn btn-default btn-fill btn-move-right visible-xs visible-sm" data-toggle="dropdown">Add new <i class="ti-plus"></i></button>
<!--                                  You can add classes for different colours on the next element -->
  <ul class="dropdown-menu dropdown-default dropdown-menu-left">
    <li class="dropdown-header">Add New</li>
    <li><a href="#">Product </a></li>
    <li><a href="#">Dough </a></li>
    <li><a href="#">Levain </a></li>
    <li><a href="#">Soaker </a></li>
    <li><a href="#">Ingredient </a></li>
  </ul>
</span>
</div>
</span>
</div>

 
        <nav class="navbar navbar-default bill hidden-sm hidden-xs" role="navigation">
    
          <div class="container-fluid">
    
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
              <ul class="nav navbar-nav bill">
    
                <li><a href="#">Products</a></li>
                <li><a href="#">Doughs</a></li>
                <li><a href="#">Levains</a></li>
                <li><a href="#">Soakers</a></li>
                <li><a href="#">Ingredients</a></li>
    					</ul>

    					<ul class="nav navbar-nav navbar-right">
    
                <li class="dropdown">

                                      <button href="#" class="dropdown-toggle btn btn-fill btn-move-right" data-toggle="dropdown" aria-expanded="false">Add new <i class="ti-plus"></i></button>
<!--                                  You can add classes for different colours on the next element -->
                                      <ul class="dropdown-menu dropdown-menu-right">
                                        <li class="dropdown-header">Add new</li>
                                        <li><a href="#">Product</a></li>
                                        <li><a href="#">Dough</a></li>
                                        <li><a href="#">Levain</a></li>
                                        <li><a href="#">Soaker</a></li>
                                        <li><a href="#">Ingredient</a></li>
                                      </ul>
                                    </li>
    					</ul>
    
            </div><!-- /.navbar-collapse -->
    
          </div><!-- /.container-fluid -->
    
        </nav>
    
    </div><!--  end navbar --> 
    </br>


<div class="container">
	<div class="row">
		<div class="col-md-12">
		<h3>
		Ingredients

		</h3>
		</br>

		<div class="table-responsive">
			<table class="table">
			    <thead>
			        <tr>
			            <th>Name</th>
			            <th>Category</th>
			            
			            <th></th>
			            
			            <th class="text-right"></th>
			        </tr>
			    </thead>
			    <tbody>
			        <tr>                     
			            <td><a>Ingredient Name</a></td>
			            <td>Bakery</td>
			            
			            
			            <td class="td-actions text-left">
			                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-sm" data-toggle="modal" data-target="#myModal">
			                    <i class="fa fa-times"></i>
			                </button>
			            </td>
			        </tr>
			        <tr>                     
			            <td><a>Ingredient Name</a></td>
                  <td>Bakery</td>
			            
			            
			            <td class="td-actions text-left">
			                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-sm" data-toggle="modal" data-target="#myModal">
			                    <i class="fa fa-times"></i>
			                </button>
			            </td>
			        </tr>
			        <tr>                     
			            <td><a>Ingredient Name</a></td>
                  <td>Bakery</td>
			            
			            
			            <td class="td-actions text-left">
			                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-sm" data-toggle="modal" data-target="#myModal">
			                    <i class="fa fa-times"></i>
			                </button>
			            </td>
			        </tr>
			        <tr>                     
			            <td><a>Ingredient Name</a></td>
                  <td>Bakery</td>
			            
			            
			            <td class="td-actions text-left">
			                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-sm" data-toggle="modal" data-target="#myModal">
			                    <i class="fa fa-times"></i>
			                </button>
			            </td>
			        </tr>
			        <tr>                     
			            <td><a>Ingredient Name</a></td>
                  <td>Bakery</td>
			            
			            
			            <td class="td-actions text-left">
			                <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-sm" data-toggle="modal" data-target="#myModal">
			                    <i class="fa fa-times"></i>
			                </button>
			            </td>
			        </tr>
			    </tbody>
			</table>
</div>


	</div>
</div>
</br>

<div class="row text-center">

<ul class="pagination"> 
    
      <li><a href="#">&laquo;</a></li>
    
      <li class="active"><a href="#">1</a></li>
    
      <li><a href="#">2</a></li>
    
      <li><a href="#">3</a></li>
    
      <li><a href="#">4</a></li>
    
      <li><a href="#">5</a></li>
    
      <li><a href="#">&raquo;</a></li>
    
    </ul>





</div>


</div>








       	</div>
      </div>
    </div>
  </div>
</div>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <p class="text-center">Are you sure you want to delete this product?</p>
      </div>
      <div class="modal-footer">
        <div class="left-side">
            <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Cancel</button>
        </div>
        <div class="divider"></div>
        <div class="right-side">
            <button type="button" class="btn btn-danger btn-simple">Delete</button>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$('.btn-tooltip').tooltip();
</script>
          

app/views/pages/orders.html.erb
    <div id="navbar">
    
        <nav class="navbar navbar-default" role="navigation">
    
          <div class="container">
    
            <div class="navbar-header">
    
    
              <%= link_to "Cocoon", root_path, class: "navbar-brand" %>
    
            </div>
    
          </div><!-- /.container-fluid -->
    
        </nav>
    
    </div><!--  end navbar --> 

</div>          
<div class="whole-page">
  <div class="wrapper">
    <div class="section section-white whole-page">
      <div class="container">
        <div class="row">
              <div class="col-md-8 col-md-offset-2">
                  <div class="tim-title text-center">
                    <h2><b>Hello, Bill</b></h2>
                    <p>Need help? <a>Watch these how-to videos</a></p>
                  </div>
              </div>
          </div>

        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <h4>
                Setup Your Customers
            </h4>
            <p>
                Setup and store all your customer’s information
            </p>
          </div>
          <div class="col-md-2">
            <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Select</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
           <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <h4>
                Create Your Products
            </h4>
            <p>
                Store your ingredients, setup your recipes and build your products
            </p>
          </div>
          <div class="col-md-2">
            <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Select</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
           <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <h4>
                Manage Your Orders
            </h4>
            <p>
                Manage your one-off or recurring orders
            </p>
          </div>
          <div class="col-md-2">
            <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Select</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
           <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <h4>
                View Your Schedules
            </h4>
            <p>
                View all the schedules and recipes for the day
            </p>
          </div>
          <div class="col-md-2">
            <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Select</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
           <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-3">
            <h4>
                Access your reports
            </h4>
            <p>
                Get access to your reports and download your data
            </p>
          </div>
         <div class="col-md-2">
            <button href="#" class="btn" data-toggle="dropdown" aria-expanded="false">Select</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
           <hr>
          </div>
        </div>
        <br>
        



       





</div>
</div>
</div>


        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Company Name A</h4>
                <h6 class="modal-title" id="myModalLabel">For Delivery</h6>
              </div>
              <div class="modal-body">
              <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th>Slice</th>
                            <th class="text-right">Qty</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>                          
                            <td>Product 1</td>
                            <td>None</td>
                            <td class="text-right">20</td>
                        </tr>
                        <tr>                          
                            <td>Product 4</td>
                            <td>Thin</td>
                            <td class="text-right">40</td>
                        </tr>
                        <tr>                          
                            <td>Product 3</td>
                            <td>Thick</td>
                            <td class="text-right">24</td>
                        </tr>
                        <tr>                          
                            <td>Product 6</td>
                            <td>None</td>
                            <td class="text-right">34</td>
                        </tr>
                        <tr>                          
                            <td>Product 2</td>
                            <td>None</td>
                            <td class="text-right">34</td>
                        </tr>
                    </tbody>
                </table>
              </div>
<hr>
              <div class="row">
                <div class="container">
                  <h3>Total = £90.00</h3>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="container">
                  <p>Ready to invoice?
                   <div class="switch ct-green"
        
                    data-on-label="<i class='fa fa-check'></i>"
                  
                    data-off-label="<i class='fa fa-times'></i>">
                  
                    <input type="checkbox" unchecked/>
                  
                  </div>
                  </p>
              </div>
              </div>
              </div>
            </div>
          </div>

              <div class="modal-footer">
                <div class="left-side">
                    <button type="button" class="btn btn-default btn-simple" data-dismiss="modal" data-toggle="modal" data-target="#myModal1">Delete Order</button>
                </div>
                <div class="divider"></div>
                <div class="right-side">
                    
                    <%= link_to "Edit Order", pages_neworder_path, class: "btn btn-info btn-simple" %>
                </div>
              </div>
            </div>
          </div>
        </div>

         <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Recurring Order</h4>
              </div>
              <div class="modal-body">
              <p>Would you like to delete only this order, all orders in the series or this and all future orders in the series?</p>
              <hr>
              <div class="row">
                <div class="col-md-6">

                  <button class="btn btn-default">Only this instance</button>

                </div>
                <div class="col-md-6">

                  <p>All other orders in the series will be retained.</p>

                </div>

              </div>
              <hr>

              <div class="row">
                <div class="col-md-6">

                  <button class="btn btn-default">All the following</button>

                </div>
                <div class="col-md-6">

                  <p>This and all the following orders will be deleted.</p>

                </div>

              </div>
              <hr>

              <div class="row">
                <div class="col-md-6">

                  <button class="btn btn-default">All orders in this series</button>

                </div>
                <div class="col-md-6">

                  <p>All orders in the series will be deleted.</p>

                </div>

              </div>









              </div>
              <div class="modal-footer">
                
                <div class="divider"></div>
                <div class="right-side">
                    <button type="button" class="btn btn-danger btn-simple">Cancel this change</button>
                </div>
              </div>
            </div>
          </div>
        </div>


		

<script type="text/javascript">
	$('.btn-tooltip').tooltip();
</script>
          